VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.private_key_path= "/Users/randy/.ssh/id_rsa"
    config.vm.box = "CentOS6.8-vagrant"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/site.yml"
        ansible.inventory_path = "provisioning/hosts"
        ansible.limit = 'all'
    end
end
